version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier
    logging:
        driver: syslog
        options:
            syslog-address: "tcp://localhost:8089"
  result:
    build: ./result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier
    logging:
        driver: syslog
        options:
            syslog-address: "tcp://localhost:8089"
  worker:
    build:
      context: ./worker
    depends_on:
      - "redis"
      - "db"
    networks:
      - back-tier
    logging:
        driver: syslog
        options:
            syslog-address: "tcp://localhost:8089"

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - back-tier
    logging:
        driver: syslog
        options:
            syslog-address: "tcp://localhost:8089"

  db:
    image: postgres:9.4
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
    logging:
        driver: syslog
        options:
            syslog-address: "tcp://localhost:8089"

volumes:
  db-data:

networks:
  front-tier:
  back-tier: